services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF:-./local/nginx.local.conf}:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service
    networks:
      - app-network

  app-service:
    image: mmcclatchy/app-service
    build:
      context: ./app-service
      dockerfile: Dockerfile
    restart: "always"
    environment:
      AUTH_SERVICE_IP: auth-service
    expose:
      - "8000"
    depends_on:
      auth-service:
        condition: service_started
    networks:
      - app-network

  auth-service:
    image: mmcclatchy/auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: "always"
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
