services:
  app-service:
    build:
      context: ./app-service
    environment:
      REST_AUTH_SERVICE_URL: http://localhost/auth
      GRPC_AUTH_SERVICE_HOST_NAME: http://auth-service:50051
    ports:
      - "8000:8000"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3000:3000"
      - "50051:50051"
    environment:
      DATABASE_URL: "postgres://postgres:${POSTGRES_PASSWORD}@db:5432"
      REST_AUTH_SERVICE_URL: http://localhost/auth
      GRPC_AUTH_SERVICE_HOST_NAME: http://auth-service:50051
      RUST_LOG: debug
      RUST_BACKTRACE: 1
      SQLX_OFFLINE: true
      REDIS_HOST_NAME: "127.0.0.1"
    restart: unless-stopped

  nginx:
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.local.conf:/etc/nginx/nginx.conf:ro
    command: null

  certbot: null
