services:
  app-service:
    build:
      context: ./app-service
    environment:
      AUTH_SERVICE_URL: localhost/auth
      AUTH_SERVICE_HOST_NAME: http://auth-service:50051

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "3000"
      - "50052:50051"
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    restart: "no"

  nginx:
    ports:
      - "8080:8080"
    volumes:
      - ./local/nginx.local.conf:/etc/nginx/nginx.conf:ro
