services:
  app-service:
    image: mmcclatchy/app-service
    build:
      context: ./app-service
      dockerfile: Dockerfile
    restart: "always"
    environment:
      AUTH_SERVICE_URL: rust-bc.markmcclatchy.com/auth
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      auth-service:
        condition: service_started
    networks:
      - app-network

  auth-service:
    image: mmcclatchy/auth-service
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    restart: "always"
    expose:
      - "50051"
    networks:
      - app-network
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
      - "50051:50051"
    volumes:
      - ./local/nginx.local.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app-service
      - auth-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
