[package]
name = "auth-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.1"
prost = "0.13.1"
env_logger = "0.11.5"
log = "0.4"

[build-dependencies]
tonic-build = "0.12.1"
env_logger = "0.11.5"
log = "0.4"
