variable "do_token" {}
variable "droplet_root_password" {}
variable "namecheap_username" {}
variable "namecheap_api_key" {}
variable "zoho_record_address" {}
variable "github_username" {}
variable "github_access_token" {}
variable "docker_username" {}
variable "docker_password" {}
