variable "do_token" {}
variable "docker_password" {}
variable "docker_username" {}
variable "domain_name" {}
variable "droplet_root_password" {}
variable "github_access_token" {}
variable "github_username" {}
variable "namecheap_api_key" {}
variable "namecheap_username" {}
variable "personal_email_address" {}
variable "postgres_password" {}
variable "postmark_auth_token" {}
variable "subdomain_name" {}
