[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
auth-proto = { path = "./proto" }
axum = "0.7.4"
tokio = { version = "1.36", features = ["full"] }
tower-http = { version = "0.5.0", features = ["fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7.0", features = ["v4", "serde"] }
async-trait = "0.1.78"
validator = { version = "0.18.1", features = ["derive"] }
tonic = "0.12.1"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["tokio"] }
env_logger = "0.11.5"
log = "0.4"

[build-dependencies]
tonic-build = "0.12.1"

[dev-dependencies]
reqwest = { version = "0.12.5", default-features = false, features = ["json"] }
fake = "=2.3.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
